INSERT INTO plant (
    common_name, scientific_name, category, description,
    light_requirement, light_notes, watering_interval_days, watering_notes,
    soil_notes, feeding_notes, pruning_notes,
    is_harvestable, days_to_maturity_min, days_to_maturity_max, harvest_notes
) VALUES
-- Vegetables
('Tomato', 'Solanum lycopersicum', 'VEGETABLE', 'Classic warm-season fruiting vegetable.',
    'FULL_SUN', 'Needs 6-8 hours of direct sun daily.', 3, 'Deep, even watering; avoid wetting foliage to reduce disease.',
    'Rich, well-drained soil with a pH of 6.0-6.8.', 'Feed every 2-3 weeks with a balanced or tomato-specific fertilizer once flowering starts.', 'Pinch off suckers and stake or cage for support.',
    true, 60, 85, 'Harvest when fully colored and slightly soft to the touch; twist gently or snip at the stem.'),
('Carrot', 'Daucus carota', 'VEGETABLE', 'Root vegetable grown for its sweet, crunchy taproot.',
    'FULL_SUN', 'Tolerates light afternoon shade in hot climates.', 4, 'Keep soil consistently moist to prevent forked or cracked roots.',
    'Loose, sandy, stone-free soil so roots can expand freely.', 'Light feeding at planting; avoid excess nitrogen, which favors leaves over roots.', 'Thin seedlings to 2-3 inches apart once established.',
    true, 60, 80, 'Harvest once shoulders (top of root) reach the desired diameter; pull gently or loosen soil first.'),
('Lettuce', 'Lactuca sativa', 'VEGETABLE', 'Fast-growing leafy green, best in cool weather.',
    'PARTIAL_SHADE', 'Some afternoon shade prevents bolting in warm weather.', 2, 'Keep soil evenly moist; shallow roots dry out quickly.',
    'Rich, well-drained soil high in organic matter.', 'Light feeding every 3 weeks with a nitrogen-rich fertilizer.', 'None needed; remove outer leaves as harvested for cut-and-come-again.',
    true, 45, 55, 'Harvest outer leaves as needed, or cut the whole head at the base once mature.'),
('Bell Pepper', 'Capsicum annuum', 'VEGETABLE', 'Sweet, warm-season fruiting vegetable.',
    'FULL_SUN', 'Needs at least 6 hours of direct sun.', 3, 'Water deeply and consistently; irregular watering causes blossom end rot.',
    'Rich, well-drained soil with a pH of 6.0-6.8.', 'Feed every 3-4 weeks once fruit begins to set.', 'Stake taller varieties to support fruit weight.',
    true, 60, 90, 'Harvest green for a tangier flavor, or leave on the plant to ripen to red/yellow/orange for sweetness.'),
('Zucchini', 'Cucurbita pepo', 'VEGETABLE', 'Prolific summer squash.',
    'FULL_SUN', 'Needs 6+ hours of direct sun.', 3, 'Deep watering at the base; avoid wetting leaves to prevent powdery mildew.',
    'Rich, well-drained soil amended with compost.', 'Feed every 2-3 weeks once flowering begins.', 'Remove any yellowing leaves to improve airflow.',
    true, 45, 55, 'Harvest young, around 6-8 inches long, for the best texture and flavor.'),
('Cucumber', 'Cucumis sativus', 'VEGETABLE', 'Vining or bush warm-season vegetable.',
    'FULL_SUN', 'Needs 6+ hours of direct sun.', 2, 'Consistent moisture is key; irregular watering leads to bitter fruit.',
    'Rich, well-drained soil high in organic matter.', 'Feed every 2-3 weeks once vines start to run.', 'Train vining types up a trellis to save space and improve airflow.',
    true, 50, 70, 'Harvest when firm and green, before they start to yellow.'),
('Spinach', 'Spinacia oleracea', 'VEGETABLE', 'Cool-season leafy green.',
    'PARTIAL_SHADE', 'Prefers cool conditions; afternoon shade helps in warmer weather.', 3, 'Keep soil evenly moist.',
    'Rich, well-drained soil high in nitrogen.', 'Light feeding every 3 weeks.', 'None needed; harvest outer leaves to extend the picking period.',
    true, 40, 45, 'Harvest outer leaves once they reach 3-4 inches, or cut the whole plant at the base.'),
('Radish', 'Raphanus sativus', 'VEGETABLE', 'Fast-growing root vegetable, great for beginners.',
    'FULL_SUN', 'Tolerates light shade.', 2, 'Keep soil consistently moist for crisp, mild roots.',
    'Loose, well-drained soil free of large debris.', 'Minimal feeding needed; too much nitrogen favors leaves over roots.', 'Thin seedlings to about 1 inch apart.',
    true, 22, 30, 'Harvest as soon as roots reach 1 inch in diameter; they turn woody and pungent if left too long.'),

-- Herbs
('Basil', 'Ocimum basilicum', 'HERB', 'Fragrant warm-season culinary herb.',
    'FULL_SUN', 'Needs 6+ hours of direct sun.', 2, 'Keep soil consistently moist but not waterlogged.',
    'Rich, well-drained soil with a pH of 6.0-7.0.', 'Feed every 4 weeks with a balanced fertilizer.', 'Pinch tips regularly to encourage bushiness and delay flowering.',
    true, 60, 90, 'Harvest leaves as needed once the plant has several sets of true leaves; regular picking encourages more growth.'),
('Mint', 'Mentha spicata', 'HERB', 'Vigorous, spreading perennial herb.',
    'PARTIAL_SHADE', 'Tolerates a range of light; some afternoon shade preferred in hot climates.', 2, 'Keep soil consistently moist; mint is thirsty.',
    'Adaptable to most soils; grow in a container to contain spreading.', 'Feed lightly every 4-6 weeks.', 'Trim back regularly to control spread and encourage bushy growth.',
    true, 60, 90, 'Harvest leaves and stems as needed once the plant is established.'),
('Rosemary', 'Salvia rosmarinus', 'HERB', 'Woody, drought-tolerant Mediterranean herb.',
    'FULL_SUN', 'Needs 6+ hours of direct sun.', 7, 'Drought-tolerant once established; let soil dry between waterings.',
    'Well-drained, slightly sandy soil; does not tolerate wet feet.', 'Minimal feeding; a light annual feed in spring is sufficient.', 'Trim after flowering to maintain shape; avoid cutting into old bare wood.',
    true, 80, 100, 'Snip sprigs as needed once the plant is well established, usually after the first growing season.'),
('Thyme', 'Thymus vulgaris', 'HERB', 'Low-growing, drought-tolerant Mediterranean herb.',
    'FULL_SUN', 'Needs 6+ hours of direct sun.', 7, 'Drought-tolerant; water only when soil is dry.',
    'Well-drained, slightly sandy or gravelly soil.', 'Minimal feeding needed.', 'Trim after flowering to keep growth compact.',
    true, 70, 90, 'Harvest sprigs just before flowering for the best flavor.'),
('Parsley', 'Petroselinum crispum', 'HERB', 'Biennial culinary herb grown as an annual.',
    'PARTIAL_SHADE', 'Tolerates part shade, especially in warmer climates.', 3, 'Keep soil evenly moist.',
    'Rich, well-drained soil high in organic matter.', 'Feed every 4-6 weeks.', 'Remove yellowing outer stems as needed.',
    true, 70, 90, 'Harvest outer stems first, allowing the center to keep producing.'),
('Cilantro', 'Coriandrum sativum', 'HERB', 'Fast-growing herb that bolts quickly in heat.',
    'PARTIAL_SHADE', 'Prefers cool conditions; afternoon shade delays bolting.', 3, 'Keep soil evenly moist.',
    'Rich, well-drained soil.', 'Light feeding every 3-4 weeks.', 'None needed; succession-sow every few weeks for a continuous supply.',
    true, 45, 70, 'Harvest leaves once the plant has several sets of true leaves, before it bolts and flowers.'),

-- Fruit
('Strawberry', 'Fragaria x ananassa', 'FRUIT', 'Low-growing perennial fruiting plant.',
    'FULL_SUN', 'Needs 6-8 hours of direct sun for best fruiting.', 3, 'Keep soil consistently moist, especially during fruiting.',
    'Rich, well-drained, slightly acidic soil (pH 5.5-6.5).', 'Feed at planting and again after harvest with a balanced fertilizer.', 'Remove runners if larger fruit is preferred over more plants.',
    true, 90, 110, 'Harvest when fruit is fully red; berries do not ripen further once picked.'),
('Blueberry Bush', 'Vaccinium corymbosum', 'FRUIT', 'Perennial shrub; takes a couple of seasons to reach full production.',
    'FULL_SUN', 'Needs at least 6 hours of direct sun.', 3, 'Keep soil consistently moist; shallow roots are sensitive to drought.',
    'Acidic, well-drained soil (pH 4.5-5.5) high in organic matter.', 'Feed in spring with an acid-forming fertilizer made for berries.', 'Prune out old or crossing canes in late winter once established.',
    true, 365, 730, 'Harvest berries once fully blue and they detach easily with a gentle tug.'),

-- Flowers
('Marigold', 'Tagetes patula', 'FLOWER', 'Easy-care annual bedding flower.',
    'FULL_SUN', 'Needs 6+ hours of direct sun for the best blooms.', 4, 'Water at the base; established plants tolerate short dry spells.',
    'Tolerates average, well-drained soil.', 'Light feeding monthly; too much fertilizer reduces blooming.', 'Deadhead spent blooms to encourage more flowers.',
    false, NULL, NULL, NULL),
('Petunia', 'Petunia x hybrida', 'FLOWER', 'Popular trailing or mounding annual.',
    'FULL_SUN', 'Needs 6+ hours of direct sun for the best blooms.', 3, 'Keep soil consistently moist, especially in containers.',
    'Rich, well-drained potting mix or garden soil.', 'Feed every 2-3 weeks during the growing season.', 'Pinch back leggy growth and deadhead to keep blooming.',
    false, NULL, NULL, NULL),
('Zinnia', 'Zinnia elegans', 'FLOWER', 'Vibrant, heat-tolerant annual cutting flower.',
    'FULL_SUN', 'Needs 6+ hours of direct sun.', 3, 'Water at the base; avoid wetting foliage to reduce mildew.',
    'Tolerates average, well-drained soil.', 'Light feeding every 4 weeks.', 'Deadhead regularly and pinch young plants to encourage branching.',
    false, NULL, NULL, NULL),
('Sunflower', 'Helianthus annuus', 'FLOWER', 'Tall, fast-growing annual known for its large flower heads.',
    'FULL_SUN', 'Needs 6-8 hours of direct sun.', 4, 'Water deeply, especially while the plant is establishing.',
    'Tolerates average soil; benefits from good drainage.', 'Light feeding at planting; avoid excess nitrogen, which delays flowering.', 'Staking recommended for taller varieties in windy spots.',
    false, NULL, NULL, NULL),

-- Houseplants
('Snake Plant', 'Dracaena trifasciata', 'HOUSEPLANT', 'Nearly indestructible, air-purifying houseplant.',
    'PARTIAL_SHADE', 'Tolerates low light but grows faster in bright, indirect light.', 14, 'Let soil dry out completely between waterings; very prone to root rot if overwatered.',
    'Well-drained potting mix, ideally formulated for cacti/succulents.', 'Feed lightly every 2 months during spring and summer only.', 'Remove damaged or yellowing leaves at the base.',
    false, NULL, NULL, NULL),
('Pothos', 'Epipremnum aureum', 'HOUSEPLANT', 'Trailing, low-maintenance houseplant.',
    'PARTIAL_SHADE', 'Tolerates low light; variegation is more vivid in brighter indirect light.', 7, 'Water when the top inch of soil feels dry.',
    'Standard well-drained potting mix.', 'Feed monthly during spring and summer.', 'Trim trailing vines to encourage bushier growth; cuttings root easily in water.',
    false, NULL, NULL, NULL),
('Peace Lily', 'Spathiphyllum wallisii', 'HOUSEPLANT', 'Flowering houseplant that tolerates low light.',
    'PARTIAL_SHADE', 'Prefers bright, indirect light; tolerates lower light with less flowering.', 7, 'Keep soil lightly moist; the plant droops noticeably when thirsty.',
    'Rich, well-drained potting mix.', 'Feed every 6-8 weeks during spring and summer.', 'Remove spent flower stalks and yellowing leaves at the base.',
    false, NULL, NULL, NULL),
('Spider Plant', 'Chlorophytum comosum', 'HOUSEPLANT', 'Easy-care houseplant known for its arching, striped leaves.',
    'PARTIAL_SHADE', 'Tolerates a wide range of light, from low to bright indirect.', 7, 'Water when the top inch of soil feels dry.',
    'Standard well-drained potting mix.', 'Feed monthly during spring and summer.', 'Trim brown leaf tips and remove plantlets to propagate.',
    false, NULL, NULL, NULL),
('Aloe Vera', 'Aloe vera', 'HOUSEPLANT', 'Succulent prized for its soothing gel.',
    'FULL_SUN', 'Needs bright light; a sunny windowsill is ideal.', 14, 'Let soil dry out completely between waterings; very drought-tolerant.',
    'Fast-draining cactus/succulent potting mix.', 'Feed sparingly, once or twice a year in spring/summer.', 'Remove any shriveled or damaged outer leaves at the base.',
    true, NULL, NULL, 'Cut a mature outer leaf close to the base and split it open to use the inner gel; only harvest a few leaves at a time.'),
('Fiddle Leaf Fig', 'Ficus lyrata', 'HOUSEPLANT', 'Popular statement houseplant with large, glossy leaves.',
    'FULL_SUN', 'Needs bright, indirect light; direct hot sun can scorch leaves.', 7, 'Water when the top inch or two of soil feels dry; sensitive to both over- and under-watering.',
    'Rich, well-drained potting mix.', 'Feed monthly during spring and summer.', 'Prune to control height and shape; wipe leaves occasionally to keep them dust-free.',
    false, NULL, NULL, NULL);
